### ISSUE TITLE
Prefer more than one time of day in preferences

### ISSUE THREAD

**Issue by EvanCooper9** [EvanCooper9/COMP3004#7]
The algorithm supports preferring 1-2 times of day (Technically 3, but that would mean they're all weighted equally).

The Preferences page should reflect this.

**Comment by coledorma** [comment]
I have fixed this issue by adding an additional letter to the end of each preferred time, corresponding to the day of the week that is the preferred, specific time off.

**Comment by EvanCooper9** [comment]
Where is this change? The code isn't updated.

**Comment by coledorma** [comment]
The reason for preferring a time of day is anticipated for 1 entry only because we have other ways that cover any of the users other preferences. There is options for the user explicitly list what specific times they aren't available and also entire days that they aren't available. Therefore, the intention of the preferred time of day is for either mornings, afternoons or nights.
